version: '3'

rpc:
  listen: 'tcp://127.0.0.1:6001'

http:
  address: '0.0.0.0:3000'
  pool:
    debug: false
    num_workers: 5
    supervisor:
      max_worker_memory: 50

server:
  command: 'php app.php'
  relay: pipes

logs:
  mode: production
  level: error
